# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs12.16
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 86400 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  events: #触发器
    - timer: #签到 #摇京豆 #店铺签到 #进店领豆
        parameters:
          name: beansign_clublottery_carexchange_shop
          cronExpression: "0 1 0 * * * *"
          enable: true
          argument: jd_bean_sign&jd_club_lottery&jd_car_exchange&jd_monk_inter_shop_sign&jd_shop
    - timer: #取关京东店铺商品 #京东抽奖机 #京东汽车 #京东秒秒币 #天天提鹅 #领金贴 #家电星推官
        parameters:
          name: unsubscribe_lotteryMachine_car_ms_jintie_xtg
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_unsubscribe&jd_lotteryMachine&jd_car&jd_ms&jd_jin_tie&jd_xtg&jd_xtg_help
    - timer: #东东农场 #东东萌宠 #京喜农场 #京东极速版红包 #美丽研究院 #手机狂欢城
        parameters:
          name: fruit_pet_jxnc2_speedsign_speedredpocke_beauty
          cronExpression: "0 5 0-18/6,8 * * * *"
          enable: true
          argument: jd_fruit&jd_pet&jd_jxnc2&jd_speed_sign&jd_speed_redpocke&jd_beauty&jd_carnivalcity
    - timer: #宠汪汪喂食 #宠汪汪 #摇钱树 #京东种豆得豆 #京喜工厂 #东东工厂 #健康社区收取能量
        parameters:
          name: feedPets_joy_moneyTree_plantBean_dreamFactory_jdfactory_healthenergy
          cronExpression: "0 3 0,6-23/1 * * * *"
          enable: true
          argument: jd_joy_feedPets&jd_joy&jd_moneyTree&jd_plantBean&jd_dreamFactory&jd_jdfactory&jd_z_health_energy
    - timer: #宠汪汪积分兑换京豆 #签到领现金 #东东小窝 #京东直播 #金榜创造营 #全民开红包
        parameters:
          name: joyreward_cash_smallhome_live
          cronExpression: "0 6 0-16/8,20 * * * *"
          enable: true
          argument: jd_joy_reward&jd_cash&jd_small_home&jd_live&jd_gold_creator&jd_redPacket
    - timer: #618动物联萌收集金币
        parameters:
          name: halfredrain_zooCollect
          cronExpression: "2 1,31 0,6-23/1 * * * *"
          enable: true
          argument: jd_zooCollect&jd_kj&jd_z_health_community
    - timer: #天天提鹅 #健康社区 #618动物联萌 #5G超级盲盒 #省钱大赢家之翻翻乐
        parameters:
          name: dailyegg_healthcommunity
          cronExpression: "0 1,30 0,5-18/2,18-21/1 * * * *"
          enable: true
          argument: jd_daily_egg&jd_zoo&jd_super_redrain&jd_mohe&jd_big_winner
    - timer: #东东超市 #京喜财富岛 #京享值PK
        parameters:
          name: cfd_superMarket
          cronExpression: "0 30 8,12,19,6-23/6 * * * *"
          enable: true
          argument: jd_cfd&jd_superMarket&jd_ddo_pk
    - timer: #京豆变动通知 #疯狂的joy #京东排行榜 #领京豆额外奖励 #闪购盲盒 #京小兑 #幸运大转盘
        parameters:
          name: beanchange_crazyjoy_rankingList_beanhome_sgmh_jxd
          cronExpression: "0 30 7 * * * *"
          enable: true
          argument: jd_bean_change&jd_crazy_joy&jd_rankingList&jd_bean_home&jd_sgmh&jd_jxd&jd_z_shop_captain&jd_market_lottery
    - timer: #金融养猪 #十元街 #京东快递 #京东赚赚 #女装盲盒 #关注有礼 #跳跳乐瓜分京豆 #新潮品牌狂欢 #京喜领88元红包 #星店长
        parameters:
          name: pigPet_syj_kd_jdzz_sign_nzmh_follow
          cronExpression: "0 20 0,9,11,21 * * * *"
          enable: true
          argument: jd_pigPet&jd_syj&jd_kd&jd_jxlhb&jd_jdzz&jd_nzmh&jd_monk_shop_follow_sku&jd_jump&jd_mcxhd&jd_star_shop
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
      JD_COOKIE: unpl=JF8EAKtnNSttWE5dDRlRHUBCS1pWWw0NQ0cHazAGAQ4NTFAATgZIFxB7XlVdXhRKEh9vZRRUWlNJXA4aCisSEXteVV5UD00QC2tkNWRaWEIZRElPKxEQe1xkXloNQx4BZ2cAU1VeQlQFHQATERNKXFRubQ9LHjNfVwBUXFlMXAESAh8iEXtfVV9YCk0UCm5vNR8zWQZUAh4KEhAYS1hTVlsBSxcFbW8GV1xZS2QEKwE; __jdc=76161171; __jdv=76161171|wjhsh.net|t_2018676952_|tuiguang|14893b7cc1634a49a55f2dbd654d5b41|1649839147908; __jdu=16498391469781173922001; areaId=1; ipLoc-djd=1-2802-0-0; PCSYCityID=CN_110000_110100_0; shshshfpa=4cfc50bc-17d9-8560-7a53-c2c44caf6cee-1649839157; shshshfpb=eYKQTUR2WH1K1Ee5MLurFMA; wxa_level=1; retina=1; cid=9; jxsid=16499296773742717980; webp=1; __jda=76161171.16498391469781173922001.1649839146.1649839148.1649929677.2; mba_muid=16498391469781173922001; visitkey=51914825222514326; PPRD_P=UUID.16498391469781173922001; share_cpin=; share_open_id=; share_gpin=; shareChannel=; source_module=; erp=; jxsid_s_u=https://home.m.jd.com/myJd/newhome.action; sc_width=1440; _gia_s_local_fingerprint=b978232b878b591fe4951d4b2bdabb8c; _gia_s_e_joint={"eid":"EN4MODQGDXCYLPCYKQLON6FW5QYW57UDSL5VZ25HCRPS3ZWQGWATPDAZC7B4EOIQYFJ3OHV6V2FPXQ2QPLS4RQZCQE","ma":"","im":"","os":"Mac OS X","ip":"120.244.230.184","ia":"","uu":"","at":"5"}; equipmentId=EN4MODQGDXCYLPCYKQLON6FW5QYW57UDSL5VZ25HCRPS3ZWQGWATPDAZC7B4EOIQYFJ3OHV6V2FPXQ2QPLS4RQZCQE; fingerprint=b978232b878b591fe4951d4b2bdabb8c; deviceVersion=100.0.4896.75; deviceOS=; deviceOSVersion=; deviceName=Chrome; wqmnx1=MDEyNjM5M3AuL2hvMzY2YWNJIDFsNUhlQzA3LzEyYTNPTyZI; __wga=1649930154899.1649929677720.1649929677720.1649929677720.2.1; jxsid_s_t=1649930155044; shshshfp=1538b3c9c1391e54d4cd0b9027fd4dc6; shshshsID=a1d3a59f238542570035ebe7ec0d5687_5_1649930174490; 3AB9D23F7A4B3C9B=EN4MODQGDXCYLPCYKQLON6FW5QYW57UDSL5VZ25HCRPS3ZWQGWATPDAZC7B4EOIQYFJ3OHV6V2FPXQ2QPLS4RQZCQE; jcap_dvzw_fp=382FzvTRs4U7t1FspqJ7CqENE1Vx5lWXJv5bpSvQ-kOgPOu1eRBzzBj-JbQSPSSEHAoEAg==; TrackerID=RETx22pQQH3KeX0BiuwIcGcgcEvJegn0VkAd7kBZ9_LMoWHPihCI91gVEQ17_m6scA6Mr2yPjo0bGJ9oyydaJZdm3ke1YWizVV9d7eDAbKNYU7vgweMT5z1jsy20JRdh; pt_key=AAJiV-_7ADBHOjQr_sQBoXpf_2PpwUQkry9qk6rWL5ZCSuLBW3ZSAlex0-c_gTALuw2qLZ8RAN0; pt_pin=jd_749a9a1927f85; pt_token=jv0poftn; pwdt_id=jd_749a9a1927f85; sfstoken=tk01mac1d1b4fa8sMSsxeDN4M3krWUYUWtv8sgM67a/erqBoW4jWWXOH5tQWH0RW8uv1sOJt1LVg165P0MdGC1GLmwL5; whwswswws=; mobilev=html5; __jdb=76161171.9.16498391469781173922001|2.1649929677; mba_sid=16499296774026507302230758969.9; __jd_ref_cls=MJingDouHome_GuidButton
      TENCENT_FUNCTION_NAME: jd
